/**
 * Pull Request creation + body building tests.
 *
 * Tests createPullRequest (via mocked execFileSync/gh), buildPrBody formatting,
 * truncation, isGhAvailable, and edge cases.
 *
 * All tests synthetic — mocks child_process to avoid real git/gh calls.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import type { PrBodyContext, PullRequestOptions } from "../src/worktree.js";

// Mock child_process before importing the module
vi.mock("node:child_process", () => ({
  execFileSync: vi.fn(),
  execSync: vi.fn(),
}));

// Mock node:fs — only stub what worktree.ts uses
vi.mock("node:fs", () => ({
  existsSync: vi.fn(() => false),
  mkdirSync: vi.fn(),
  rmSync: vi.fn(),
  writeFileSync: vi.fn(),
  readFileSync: vi.fn(() => ""),
  appendFileSync: vi.fn(),
}));

import { execFileSync } from "node:child_process";
import { buildPrBody, createPullRequest, isGhAvailable } from "../src/worktree.js";

const mockExec = execFileSync as unknown as ReturnType<typeof vi.fn>;

beforeEach(() => {
  vi.resetAllMocks();
});

// ── buildPrBody ──────────────────────────────────────────────────

describe("buildPrBody", () => {
  const baseContext: PrBodyContext = {
    instanceName: "worker-1",
    skills: [
      { name: "implement", status: "complete", durationSec: 120, issueCount: 2 },
      { name: "qa", status: "complete", durationSec: 45, issueCount: 0 },
    ],
    pipelineDurationSec: 165,
    costUsd: 0.47,
  };

  it("includes instance name and pipeline", () => {
    const body = buildPrBody(baseContext);
    expect(body).toContain("**Instance:** worker-1");
    expect(body).toContain("**Pipeline:** implement → qa");
  });

  it("formats duration and cost", () => {
    const body = buildPrBody(baseContext);
    expect(body).toContain("**Duration:** 2m 45s");
    expect(body).toContain("**Cost:** $0.470");
  });

  it("renders skills table", () => {
    const body = buildPrBody(baseContext);
    expect(body).toContain("| implement | complete | 2m | 2 |");
    expect(body).toContain("| qa | complete | 45s | 0 |");
  });

  it("includes TODO title when provided", () => {
    const body = buildPrBody({ ...baseContext, todoTitle: "P3: Fix the thing" });
    expect(body).toContain("### TODO Item");
    expect(body).toContain("**P3: Fix the thing**");
  });

  it("omits TODO section when not provided", () => {
    const body = buildPrBody(baseContext);
    expect(body).not.toContain("### TODO Item");
  });

  it("renders oracle decisions capped at 10", () => {
    const decisions = Array.from({ length: 15 }, (_, i) => ({
      question: `Question ${i}`,
      chosen: `Answer ${i}`,
      confidence: 8,
    }));
    const body = buildPrBody({ ...baseContext, oracleDecisions: decisions });
    expect(body).toContain("### Oracle Decisions");
    expect(body).toContain('"Question 0"');
    expect(body).toContain('"Question 9"');
    expect(body).not.toContain('"Question 10"');
    expect(body).toContain("... and 5 more decisions");
  });

  it("renders test results", () => {
    const body = buildPrBody({ ...baseContext, testsPassed: true, testDurationSec: 12.3 });
    expect(body).toContain("Pre-merge tests: PASSED (12.3s)");
  });

  it("renders issues capped at 20", () => {
    const issues = Array.from({ length: 25 }, (_, i) => ({
      description: `Issue ${i}`,
      status: i < 20 ? "fixed" : "open",
    }));
    const body = buildPrBody({ ...baseContext, issues });
    expect(body).toContain("[FIXED] Issue 0");
    expect(body).toContain("... and 5 more issues");
  });

  it("truncates body exceeding 60000 chars", () => {
    const longDecisions = Array.from({ length: 10 }, (_, i) => ({
      question: "x".repeat(7000),
      chosen: "y",
      confidence: 5,
    }));
    const body = buildPrBody({ ...baseContext, oracleDecisions: longDecisions });
    expect(body.length).toBeLessThanOrEqual(60_000);
    expect(body).toContain("... truncated (exceeded GitHub body limit)");
  });

  it("includes GaryClaw footer", () => {
    const body = buildPrBody(baseContext);
    expect(body).toContain("Generated by [GaryClaw]");
  });

  it("handles single skill", () => {
    const body = buildPrBody({
      instanceName: "worker-1",
      skills: [{ name: "qa", status: "complete" }],
      costUsd: 0.1,
    });
    expect(body).toContain("**Pipeline:** qa");
    expect(body).toContain("| qa | complete | — | — |");
  });

  it("handles empty oracle decisions", () => {
    const body = buildPrBody({ ...baseContext, oracleDecisions: [] });
    expect(body).not.toContain("### Oracle Decisions");
  });
});

// ── isGhAvailable ─────────────────────────────────────────────────

describe("isGhAvailable", () => {
  it("returns true when gh auth status succeeds", () => {
    mockExec.mockReturnValue("");
    expect(isGhAvailable("/repo")).toBe(true);
    expect(mockExec).toHaveBeenCalledWith("gh", ["auth", "status"], expect.objectContaining({ cwd: "/repo" }));
  });

  it("returns false when gh auth status throws", () => {
    mockExec.mockImplementation(() => { throw new Error("gh not found"); });
    expect(isGhAvailable("/repo")).toBe(false);
  });
});

// ── createPullRequest ────────────────────────────────────────────

describe("createPullRequest", () => {
  const baseOptions: PullRequestOptions = {
    title: "GaryClaw: implement feature X",
    body: "## Summary\nDid stuff.",
    baseBranch: "main",
  };

  function setupGhSuccess() {
    mockExec.mockImplementation((cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "auth") return ""; // auth check
      if (cmd === "git" && args[0] === "push") return ""; // push
      if (cmd === "gh" && args[0] === "pr" && args[1] === "list") return "[]"; // no existing PR
      if (cmd === "gh" && args[0] === "pr" && args[1] === "create") return "https://github.com/owner/repo/pull/42";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "merge") return ""; // auto-merge
      return "";
    });
  }

  it("creates PR successfully", () => {
    setupGhSuccess();
    const result = createPullRequest("/repo", "worker-1", baseOptions);
    expect(result.created).toBe(true);
    expect(result.prNumber).toBe(42);
    expect(result.prUrl).toBe("https://github.com/owner/repo/pull/42");
    expect(result.autoMergeEnabled).toBe(true);
  });

  it("returns failure when gh is not available", () => {
    mockExec.mockImplementation(() => { throw new Error("not found"); });
    const result = createPullRequest("/repo", "worker-1", baseOptions);
    expect(result.created).toBe(false);
    expect(result.reason).toContain("gh CLI not available");
  });

  it("returns failure when push fails", () => {
    mockExec.mockImplementation((cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "auth") return "";
      if (cmd === "git" && args[0] === "push") throw new Error("push rejected");
      return "";
    });
    const result = createPullRequest("/repo", "worker-1", baseOptions);
    expect(result.created).toBe(false);
    expect(result.reason).toContain("Push failed");
  });

  it("updates existing PR instead of creating new", () => {
    mockExec.mockImplementation((cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "auth") return "";
      if (cmd === "git" && args[0] === "push") return "";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "list") return JSON.stringify([{ number: 99 }]);
      if (cmd === "gh" && args[0] === "pr" && args[1] === "edit") return "";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "view") return JSON.stringify({ url: "https://github.com/owner/repo/pull/99" });
      if (cmd === "gh" && args[0] === "pr" && args[1] === "merge") return "";
      return "";
    });
    const warnings: string[] = [];
    const result = createPullRequest("/repo", "worker-1", {
      ...baseOptions,
      onWarn: (msg) => warnings.push(msg),
    });
    expect(result.created).toBe(true);
    expect(result.prNumber).toBe(99);
    expect(warnings.some((w) => w.includes("Updated existing PR #99"))).toBe(true);
  });

  it("handles auto-merge failure gracefully", () => {
    mockExec.mockImplementation((cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "auth") return "";
      if (cmd === "git" && args[0] === "push") return "";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "list") return "[]";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "create") return "https://github.com/owner/repo/pull/10";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "merge") throw new Error("auto-merge not enabled");
      return "";
    });
    const warnings: string[] = [];
    const result = createPullRequest("/repo", "worker-1", {
      ...baseOptions,
      onWarn: (msg) => warnings.push(msg),
    });
    expect(result.created).toBe(true);
    expect(result.autoMergeEnabled).toBe(false);
    expect(warnings.some((w) => w.includes("Auto-merge not enabled"))).toBe(true);
  });

  it("skips auto-merge when autoMerge is false", () => {
    setupGhSuccess();
    const result = createPullRequest("/repo", "worker-1", {
      ...baseOptions,
      autoMerge: false,
    });
    expect(result.created).toBe(true);
    expect(result.autoMergeEnabled).toBe(false);
    // Verify gh pr merge was never called
    const mergeCalls = mockExec.mock.calls.filter(
      (c: any[]) => c[0] === "gh" && c[1]?.[0] === "pr" && c[1]?.[1] === "merge",
    );
    expect(mergeCalls).toHaveLength(0);
  });

  it("passes draft flag", () => {
    setupGhSuccess();
    createPullRequest("/repo", "worker-1", { ...baseOptions, draft: true });
    const createCall = mockExec.mock.calls.find(
      (c: any[]) => c[0] === "gh" && c[1]?.[0] === "pr" && c[1]?.[1] === "create",
    );
    expect(createCall?.[1]).toContain("--draft");
  });

  it("passes labels", () => {
    setupGhSuccess();
    createPullRequest("/repo", "worker-1", { ...baseOptions, labels: ["bot", "auto"] });
    const createCall = mockExec.mock.calls.find(
      (c: any[]) => c[0] === "gh" && c[1]?.[0] === "pr" && c[1]?.[1] === "create",
    );
    expect(createCall?.[1]).toContain("--label");
    expect(createCall?.[1]).toContain("bot");
    expect(createCall?.[1]).toContain("auto");
  });

  it("passes reviewers", () => {
    setupGhSuccess();
    createPullRequest("/repo", "worker-1", { ...baseOptions, reviewers: ["alice"] });
    const createCall = mockExec.mock.calls.find(
      (c: any[]) => c[0] === "gh" && c[1]?.[0] === "pr" && c[1]?.[1] === "create",
    );
    expect(createCall?.[1]).toContain("--reviewer");
    expect(createCall?.[1]).toContain("alice");
  });

  it("uses specified merge method", () => {
    setupGhSuccess();
    createPullRequest("/repo", "worker-1", { ...baseOptions, mergeMethod: "rebase" });
    const mergeCall = mockExec.mock.calls.find(
      (c: any[]) => c[0] === "gh" && c[1]?.[0] === "pr" && c[1]?.[1] === "merge",
    );
    expect(mergeCall?.[1]).toContain("--rebase");
  });

  it("returns failure when PR creation fails", () => {
    mockExec.mockImplementation((cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "auth") return "";
      if (cmd === "git" && args[0] === "push") return "";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "list") return "[]";
      if (cmd === "gh" && args[0] === "pr" && args[1] === "create") throw new Error("network error");
      return "";
    });
    const result = createPullRequest("/repo", "worker-1", baseOptions);
    expect(result.created).toBe(false);
    expect(result.reason).toContain("PR creation failed");
  });
});
