/**
 * Notifier — macOS notifications and job summary files.
 *
 * Uses osascript for native macOS notifications.
 * Graceful no-op if osascript is unavailable.
 */

import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { Job, DaemonConfig } from "./types.js";

/**
 * Send a macOS notification for a completed job.
 */
export function notifyJobComplete(job: Job, config: DaemonConfig): void {
  if (!config.notifications.enabled || !config.notifications.onComplete) return;

  const title = "GaryClaw Job Complete";
  const message = `/${job.skills.join(" → /")} finished ($${job.costUsd.toFixed(3)})`;
  sendNotification(title, message);
}

/**
 * Send a macOS notification for a failed job.
 */
export function notifyJobError(job: Job, config: DaemonConfig): void {
  if (!config.notifications.enabled || !config.notifications.onError) return;

  const title = "GaryClaw Job Failed";
  const message = `/${job.skills.join(" → /")} failed: ${job.error ?? "unknown error"}`;
  sendNotification(title, message);
}

/**
 * Send a macOS notification for an escalated decision.
 */
export function notifyEscalation(question: string, config: DaemonConfig): void {
  if (!config.notifications.enabled || !config.notifications.onEscalation) return;

  const title = "GaryClaw Escalation";
  const message = question.slice(0, 200);
  sendNotification(title, message);
}

/**
 * Write a summary.md file for a completed/failed job.
 */
export function writeSummary(job: Job, jobDir: string): void {
  mkdirSync(jobDir, { recursive: true });

  const lines: string[] = [];
  lines.push(`# Job Summary — ${job.id}`);
  lines.push("");
  lines.push(`**Status:** ${job.status}`);
  lines.push(`**Skills:** ${job.skills.map((s) => `/${s}`).join(" → ")}`);
  lines.push(`**Triggered by:** ${job.triggeredBy} (${job.triggerDetail})`);
  lines.push(`**Enqueued:** ${job.enqueuedAt}`);
  if (job.startedAt) lines.push(`**Started:** ${job.startedAt}`);
  if (job.completedAt) lines.push(`**Completed:** ${job.completedAt}`);
  lines.push(`**Cost:** $${job.costUsd.toFixed(3)}`);

  if (job.error) {
    lines.push("");
    lines.push(`## Error`);
    lines.push(job.error);
  }

  if (job.reportPath) {
    lines.push("");
    lines.push(`## Report`);
    lines.push(`See: ${job.reportPath}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("*Generated by GaryClaw Daemon*");

  writeFileSync(join(jobDir, "summary.md"), lines.join("\n"), "utf-8");
}

/**
 * Send a macOS notification via osascript. No-op if unavailable.
 */
export function sendNotification(title: string, message: string): boolean {
  try {
    const escapedTitle = title.replace(/"/g, '\\"');
    const escapedMessage = message.replace(/"/g, '\\"');
    execSync(
      `osascript -e 'display notification "${escapedMessage}" with title "${escapedTitle}"'`,
      { timeout: 5000, stdio: "ignore" },
    );
    return true;
  } catch {
    return false;
  }
}
